name: swallowing_app
description: A flutter project created using MobX and Provider.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # The following adds the shared pref as a dependency in your application
  shared_preferences: ^0.5.10

  # A composable, Future-based library for making HTTP requests.
  http: ^0.12.2

  # Flogs, a powerful logging framework
  f_logs: ^1.2.2

  # MobX is a library for reactively managing the state of your applications. Use the power of
  # observables, actions, and reactions to supercharge your Dart and Flutter apps.
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2

  # An helper to easily exposes a value using InheritedWidget without having to write one.
  provider: ^4.3.2+1

  # String validation and sanitization for Dart. Dart 2-compatible version of validator
  validators: ^2.0.1

  # A powerful Http client for Dart
  dio: 3.0.10

  # A flexible widget for user notification. Customize your text, button, duration, animations
  # and much more. For Android devs, it is made to replace Snackbars and Toasts.
  flushbar: ^1.10.4

  # Material Dialog
  material_dialog: ^0.0.9

  # This package provides internationalization and localization facilities, including message
  # translation, plurals and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.16.1

  # Dependency injection
  inject:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject
      ref: 7c3cbf6

  # A highly configurable navigation bar with emphasis for the selected item.
  ff_navigation_bar: ^0.1.5

  # A Flutter plugin for launching a URL in the mobile platform.
  url_launcher: ^5.7.10

  # A Flutter plugin for iOS, Android and Web for playing back video on a Widget surface.
  video_player: ^1.0.1

  # The video player for Flutter with a heart of gold.
  chewie: ^0.12.2

  # This plugin generates thumbnail from video file or URL. It returns image in memory or writes
  # into a file. It offers rich options to control the image format, resolution and quality.
  video_thumbnail: ^0.2.5+1

  # A Flutter plugin for iOS and Android for picking images from the image library, and taking
  # new pictures with the camera.
  image_picker: ^0.6.7+22

  # A Flutter plugin for finding commonly used locations on the filesystem.
  path_provider: ^1.6.27

  # A Flutter plugin for iOS and Android allowing access to the device cameras.
  camera: ^0.7.0+2

  # A platform-independent package for parsing and serializing various HTTP-related formats.
  http_parser: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.5
  mobx_codegen: ^1.1.0+1
  json_serializable: ^3.4.1
  build_runner: ^1.10.2
  source_gen: 0.9.6
  analyzer: ^0.39.12
  inject_generator:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject_generator
      ref: 7c3cbf6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/icons/
  - assets/lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Kanit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Kanit-Light.ttf
          weight: 300
        - asset: assets/fonts/Kanit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Kanit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Kanit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Kanit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Kanit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Kanit-Black.ttf
          weight: 900
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
